### ISSUE TITLE
when will the paper relsease

### ISSUE THREAD

**Issue by wangyawei3521** [sled-group/CycleNet#1]
great work, looking forward to it, but the paper link not work , when will the paper release?

**Comment by Mars-tin** [comment]
Our paper is accepted to NeurIPS 2023 and we will release a preprint soon. Thanks for the inquiry and please stay tuned!

**Comment by Mars-tin** [comment]
The paper is now available on arxiv: https://arxiv.org/abs/2310.13165

**Comment by wzr1201** [comment]
> The paper is now available on arxiv: https://arxiv.org/abs/2310.13165

hi, will you release the code for training ManiCups dataset? Looking forward to a reply， thanks very much
