### ISSUE TITLE
How to provide appropriate source prompts and target prompts

### ISSUE THREAD

**Issue by qty0228** [sled-group/CycleNet#3]
Your work looks impressive. I would like to ask, in the summer2winter task, what kind of source prompts and target prompts are provided?

**Comment by h6kplus** [comment]
For baselines like prompt2promt and cyclediffusion that need these prompts, we used "summer" as the source prompt and "winter" as the target prompt. For baseline pix2pixzero, we followed the authors' practice by first generating the embedding of summer and winter and then used them to edit the image.
